# Generated by Django 5.1.6 on 2025-02-25 16:02

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.CharField(max_length=10)),
                ('expire_date', models.DateTimeField(default=accounts.models.time_default)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
