# Generated by Django 5.1.6 on 2025-02-26 08:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=200)),
                ('expire_date', models.DateTimeField(default=accounts.models.time_default)),
            ],
        ),
    ]
